runtime: java
env: flex

handlers:
- url: /.*
  script: this field is required, but ignored
  
readiness_check:
  app_start_timeout_sec: 1800
  
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6