runtime: java
env: flex

handlers:
- url: /.*
  script: this field is required, but ignored
  
automatic_scaling
	max_instances: 1
	min_instances: 1
	max_idle_instances: 1
	min_idle_instances: 1
	min_pending_latency: 3000ms