# Spring properties
spring:
  application:
    name: api-gateway  # Identify this application

# Server
server:
#  port: @http.port@   # HTTP (Tomcat) port
#  ssl:
#    enabled: true

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:1111/eureka/
      defaultZone: https://cartonwale-225319.appspot.com/eureka/
  instance:
    #securePortEnabled: true
    #nonSecurePortEnabled: false
    #leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
    hostname: cartonwale-api-gateway.appspot.com

# Api-Gate-Way
zuul:
  prefix: /api
  routes:
    auth-service:
      path: /auth-service/**
      #url: https://cartonwale-auth-service.appspot.com
      serviceId: AUTH-SERVICE
      #stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie
      
    provider-service:
      path: /provider-service/**
      #url: https://cartonwale-provider-service.appspot.com
      serviceId: PROVIDER-SERVICE
      #stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie
  #host:
    #connect-timeout-millis: 5000
    #socket-timeout-millis: 60000
    
ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    #IsSecure: true
    eureka:
     enabled: true

      
# Increase the Hystrix timeout to 60s (globally)

            
      