# Configure this Discovery Server
eureka:
  instance:
    hostname: cartonwale.appspot.com
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
       
# HTTP Server
#server:
#  port: @http.port@