# Configure this Discovery Server
eureka:
  instance:
    #hostname: localhost
    hostname: cartonwale-225319.appspot.com
    #securePortEnabled: true
    #nonSecurePortEnabled: false
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
       
# HTTP Server
#server:
#  port: @http.port@
#  ssl:
#    enabled: true