# Spring properties
spring:
  application:
    name: product-service

# Mongo properties
  data:
    mongodb:
      uri: mongodb://appuser:NAmd3SgmePaNnBvc@biz2biz-shard-00-00-2e6r2.mongodb.net:27017,biz2biz-shard-00-01-2e6r2.mongodb.net:27017,biz2biz-shard-00-02-2e6r2.mongodb.net:27017/test?ssl=true&replicaSet=biz2biz-shard-0&authSource=admin&retryWrites=true
      #port: @mongo.port@
      database: @mongo.database@
      #username: @mongo.username@
      #password: @mongo.password@


# HTTP Server
server:
  port: 80
#  ssl:
#    enabled: true
  
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      abc: 1
      #defaultZone: http://localhost:1111/eureka/
      defaultZone: https://cartonwale-225319.appspot.com/eureka/
  instance:
    #securePortEnabled: true
    #nonSecurePortEnabled: false
    #leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
    hostname: cartonwale-product-service.appspot.com
    #hostname: localhost

# Auth JWT
jwt:
  header: Authorization
  secret: carton_secret
  expiration: 172800 #seconds
  route:
    authentication:
      path: auth
      refresh: refresh

